# Generated by Django 4.1.4 on 2023-01-24 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Active')], default=0, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'Processing'), (2, 'Finished')], default=0, verbose_name='Status')),
                ('input', models.JSONField(blank=True, null=True, verbose_name='Input')),
                ('output', models.JSONField(blank=True, null=True, verbose_name='Output')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='flow.flow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('node_type', models.IntegerField(choices=[(0, 'Trigger'), (1, 'Action'), (2, 'Logic')], verbose_name='Node Type')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('sub_nodes', models.ManyToManyField(blank=True, to='flow.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('accepts', models.ManyToManyField(blank=True, to='flow.optiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='flow.node')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='flow.optiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'Processing'), (2, 'Finished')], default=0, verbose_name='Status')),
                ('input', models.JSONField(blank=True, null=True, verbose_name='Input')),
                ('output', models.JSONField(blank=True, null=True, verbose_name='Output')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flow.job')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flow.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='flow.node'),
        ),
    ]
