# Generated by Django 4.1.4 on 2023-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_list',
            field=models.BooleanField(default=False, verbose_name='Is List'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Paused')], default=0, verbose_name='Status'),
        ),
    ]
