# Generated by Django 4.1.4 on 2023-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_option_is_list_alter_flow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('String', 'string'), ('Number', 'number'), ('Boolean', 'boolean'), ('Object', 'object')], max_length=100, verbose_name='OptionType'),
        ),
        migrations.DeleteModel(
            name='OptionType',
        ),
    ]
