# Generated by Django 4.1.4 on 2023-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_alter_option_option_type_delete_optiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='Params'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('action', 'Action'), ('logic', 'Logic')], max_length=100, verbose_name='Node Type'),
        ),
    ]
